reviewers:
  # The default reviewers
  defaults:
    - repository-owners # group

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    repository-owners:
      - StephanGuingor # username
      - XimeSan # username
      - marriagav


files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**':
    - repository-owners # group

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: true

  # Randomly pick reviewers up to this number.
  # Do not set this option if you'd like to assign all matching reviewers.
  # number_of_reviewers: 2