version: 0.0
os: linux
files:
 - source: /
   destination: /
hooks:
  Install:
    - location: scripts/setup.sh
      timeout: 100
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 100
