version: "3.7"

services:
  server:
    image: "nginx:alpine"
    depends_on:
      - rest-client
    networks:
            - my-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./webserver.conf:/etc/nginx/conf.d/default.conf"
  mariadb:
    image: "mariadb:latest"
    networks:
            - my-network
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=test
      - MARIADB_USER=test
      - MARIADB_PASSWORD=test
    # /etc/mysql/conf.d can map any conf file
    ports:
      - "3306:3306"
    volumes:
      - "../data:/var/lib/mysql"

  rest-client:
    image: stephantec/rest-client:latest
    container_name: flask
    build: ./rest-client
    # restart: always
    depends_on:
      - mariadb
    networks:
      my-network:
        aliases:
          - flask-app

networks:
  my-network:
