version: "3.9"

services:
# here we should install flask, and set the approppiate ports, commands
# we should not forget to use nginx o any other reverse proxy
  app:
    environment:
      SQL_HOST: mariadb
      SQL_USER: debug
      SQL_PASSWORD: secret
      SQL_DB: test

  mariadb:
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
