name: build-deploy

on:
  push:
    branches: 
      - "master"

jobs:
  docker-mqtt:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 
        uses: docker/build-push-action@v2
        with:
          context: mqtt-client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mqtt-client:latest

  docker-rest:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 
        uses: docker/build-push-action@v2
        with:
          context: rest-client
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rest-client:latest

  deploy-production:
    runs-on: ubuntu-latest
    needs: [docker-mqtt,docker-rest]
    if: github.ref == 'refs/heads/master'
    steps:
    # the checkout action persists the passed credentials by default
    # subsequent git commands will pick them up automatically
    - uses: actions/checkout@v2
    - uses: everlytic/branch-merge@1.1.2
      with:
        token: ${{ secrets.PAT }}
        source_ref: ${{ github.ref }}
        target_branch: 'production'
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
        
